### ISSUE TITLE
Enhance reduce-tracking-mode

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#1014]
For now, `reduce-tracking-mode` is not doing much, while it should do lots of things to fight tracking. This is the list of most trackable things in Nyxt that, I believe, we should tweak in `reduce-tracking-mode` (some are not tweakable yet) (based on tests from [Panopticlick](https://panopticlick.eff.org).):

- [X] User Agent
    - Solution: do what [Chameleon (User Agent Spoofing)](https://github.com/sereneblue/chameleon) does or Just set User Agent it to a recent Chrome/Safari version.
- [ ] HTTP ACCEPT headers
     - Need libsoup bindings before we can do anything with it :(
- [x] Time Zone Offset
     - It's -300 (quite an unusual offset), but I don't know what to do with it.
- [ ] Hash of canvas fingerprint
     - Solution: do what [CanvasBlocker](https://github.com/kkapsner/CanvasBlocker) does?
- [ ] Hash of WebGL
    - Is computed from WebGL canvas. Disabling WebGl should work against it, but it somewhy doesn't (#1006).
- [ ] Touch support
    - Gesture features of WebKit? Are they about touch devices?
    - Solution: set `webkit-settings-enable-webgl-back-forward-navigation-gestures` to nil?
- [ ] AudioContext fingerprint
    - Not really avoidable except for using a typical hardware.

Thoughts?

**Comment by Ambrevar** [comment]
I was going to open a similar issue, thanks for taking this initiative!

> - User Agent
>     - Solution: do what [Chameleon (User Agent Spoofing)](https://github.com/sereneblue/chameleon) does or Just set User Agent it to a recent Chrome/Safari version.

Easy.

> - HTTP ACCEPT headers
>      - Need libsoup bindings before we can do anything with it :(

Should be easy since libsoup does not depend on GTK.

> - Time Zone Offset
>      - It's -300 (quite an unusual offset), but I don't know what to do with it.
> - Hash of canvas fingerprint
>      - Solution: do what [CanvasBlocker](https://github.com/kkapsner/CanvasBlocker) does?
> - Hash of WebGL
>     - Is computed from WebGL canvas. Disabling WebGl should work against it, but it somewhy doesn't (#1006).
> - Touch support
>     - Gesture features of WebKit? Are they about touch devices?
>     - Solution: set `webkit-settings-enable-webgl-back-forward-navigation-gestures` to nil?
> - AudioContext fingerprint
>     - Not really avoidable except for using a typical hardware.

No idea about the rest, only trying will tell! :)

**Comment by aartaka** [comment]
Here's some useful info from WebKit: https://trac.webkit.org/wiki/Fingerprinting

**Comment by aadcg** [comment]
It would be unwise to rely on libsoup bindings since that would mean that we'd need an ffi-generic to handle the renderer's HTTP client in a renderer-agnostic way.
