### ISSUE TITLE
Expand WebExtensions support

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#2114]
Our current WebExtensions support is experimental, and there's not much extensions we can run with it. We need to expand it. We can start by supporting uBlock-required APIs, as this is a sane minimum for a WebExtensions support to have. Here's a (mostly copy-pasted from #1762) list of things to fix/add/think about:

- [ ] runtime.getURL returns data: URLs which are only suitable for resource loading, while [being a security hole when navigated to](https://blog.mozilla.org/security/2017/11/27/blocking-top-level-navigations-data-urls-firefox-59/). We need to use the recent mechanism from #2049 to build and fetch `web-extension://` scheme links.
- [ ] Permissions 
  - [x] Implemented on Lisp-side.
  - [x] Load-time ones on C-side.
  - [ ] Runtime change of permission on the C-side.
- [ ] Add/fix event filters. Commits between 9c942daf36697c5666d7762e9a48c727582df207 and d9648bbbedfcb5b83f0184231d4d91524ecb1fbc add an experimental implementation of it, but it's unreliable and most likely broken.
- [ ] Commands.
- [ ] Option pages.
- [ ] Supporting more manifest.json keys (alphabetic order):
  - [X] browser_action
  - [X] content_scripts
  - [X] description
  - [X] homepage_url
  - [X] icons
  - [X] manifest_version
  - [X] name
  - [X] version
  - [ ] author
  - [ ] background
  - [ ] browser_specific_settings
  - [ ] chrome_settings_overrides
  - [ ] chrome_url_overrides
  - [ ] commands
  - [ ] content_security_policy
  - [ ] default_locale
  - [ ] developer
  - [ ] devtools_page
  - [ ] dictionaries
  - [ ] externally_connectable
  - [ ] incognito
  - [ ] offline_enabled
  - [ ] omnibox (`set-url` integration?)
  - [ ] optional_permissions
  - [ ] options_page
  - [ ] options_ui
  - [ ] page_action
  - [X] permissions
  - [ ] protocol_handlers
  - [ ] short_name
  - [ ] sidebar_action
  - [ ] storage
  - [ ] theme (integrate with #1889?)
  - [ ] theme_experiment
  - [ ] user_scripts (requires #2021?)
  - [ ] version_name
  - [ ] web_accessible_resources
- Supporting uBlock-used APIs (duplicated in #32, will be tracked there from now on):
  - Methods (alphabetically, with unimplemented on top):
    - [ ] browser.browserAction.setPopup -- easy
    - [ ] browser.commands.getAll -- easy
    - [ ] browser.commands.reset -- easy
    - [ ] browser.commands.update -- easy
    - [ ] browser.i18n.getMessage -- easy?
    - [ ] browser.runtime.connect
    - [ ] browser.runtime.reload
    - [ ] browser.tabs.move -- easy
    - [ ] browser.webRequest.filterResponseData
    - [ ] browser.webRequest.handlerBehaviorChanged
    - [X] browser.runtime.getBrowserInfo
    - [X] browser.runtime.getManifest
    - [X] browser.runtime.getURL
    - [X] browser.tabs.create
  - Variables and types (will be mostly easy to do):
    - [ ] browser.runtime.lastError
    - [ ] browser.windows.WINDOW_ID_NONE -- easy
    - [ ] browser.webRequest.ResourceType -- easy
  - Events (alphabetically, with unimplemented on top, hardest to do as they require modifications all over Nyxt sources):
    - [ ] browser.browserAction.onClicked -- easy
    - [ ] browser.commands.onCommand -- easy
    - [ ] browser.runtime.onConnect
    - [ ] browser.runtime.onUpdateAvailable
    - [x] browser.tabs.onActivated
    - [x] browser.tabs.onCreated -- easy
    - [x] browser.tabs.onRemoved -- easy
    - [ ] browser.tabs.onUpdated
    - [ ] browser.webNavigation.onCommitted
    - [ ] browser.webNavigation.onCreatedNavigationTarget
    - [ ] browser.webRequest.onBeforeRequest
    - [ ] browser.webRequest.onHeadersReceived
    - [ ] browser.windows.onFocusChanged -- easy
  - Non-mandatory but cool APIs because uBlock uses them to provide more features:
    - [ ] browser.dns
    - [ ] browser.privacy
    - [ ] browser.menus

**Comment by Ambrevar** [comment]
In #1762 you also mentioned:

> Memory is not freed everywhere it needs to be. This can clutter our memory with time. Thus, C-side of things asks for more memory discipline.

Is this still valid?
