### ISSUE TITLE
3-series release roadmap

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2303]
So... The light is showing at the end of the tunnel, at last!
3.0.0 is looming close!

I suggest we first release a `3-pre-release-1` like we did in the past because:
- we need some feedback, testing, etc.
- the packaging process has changed a little now that we include the source.  We want to make sure this works as expected for everyone.

What's left to do?

- [ ] All the `3.0` issues: https://github.com/atlas-engineer/nyxt/issues?q=is%3Aissue+is%3Aopen+label%3A3.0
  (Most of them are trivial matters like documentation, answering a question, etc.)
- [ ] Review the mode docstrings.
- [ ] Review the _package_ docstrings.  These have been neglected and I believe we should put more emphasis on them.  I think they can serve as good entry points and direct the user to the other important docstrings in the package.
- [ ] Make sure external libraries like https://github.com/atlas-engineer/nfiles/ are accessible to newcomers.  Examples should be readily available.
- [ ] Update the ChangeLog with everything new since 2.2.4 (lots of work! :p)
- [ ] Test every command and mode.  (As part of a test suite if possible.)
- [ ] For everyone joining the party, run the `nyxt` binary locally for your regular browsing, as much as possible, for days.  Report crashes and their frequency.
- [ ] Battle-test the startup sequence.  We should no longer fail so mysteriously on startup and recover as much as we can to not leave the user in the dark.  See https://github.com/atlas-engineer/nyxt/issues/2286 for that.
- [ ] Test (and complete?) the graphical customization ("Common settings"): https://github.com/atlas-engineer/nyxt/issues/2296

Anything else?

**Comment by aadcg** [comment]
Oh boy, let's not add anything else for now :weary:.

**Comment by hendursaga** [comment]
> run the nyxt binary locally for your regular browsing, as much as possible, for days. Report crashes and their frequency.

Woah woah, you're asking to DOGFOOD? :sweat_smile:

**Comment by Ambrevar** [comment]
We're getting really close!

The last blocking tasks before `3-pre-release-1`:
- https://github.com/atlas-engineer/nyxt/issues/2296
- https://github.com/atlas-engineer/nyxt/issues/2363 (@aartaka is on it).

@jmercouris @aadcg @aartaka If you've got time, could you help updating the migration guide and the change log?  It's lots of work, we won't be too many ;)

**Comment by aartaka** [comment]
I'm currently working on Plump-based text search on `lispy-search` branch. It'd be nice if you wait for it too, as it should shorten and beautify the code a lot (while being a tiny bit backwards-incompatible...)

**Comment by Ambrevar** [comment]
Roger that! :)

**Comment by aadcg** [comment]
I don't any reason why we shouldn't ship 3.0 with recursive search! It should be ready soon.

**Comment by Ambrevar** [comment]
Huhuhu, well, the reason is that we've been "delaying" it for month and there is still lots of work ahead :)

I'm all for merging in new features, but remember that with every new feature comes its load of new issues, and we'd rather have less issues and less features than more issues and more features for a brand new stable release ;)

In any case, when things are backward compatible they can be released with 3.1 even if it's just 2 weeks later.

**Comment by aadcg** [comment]
Fair enough!

**Comment by aadcg** [comment]
Regardless, I assume that re-writing something as fundamental as `search-buffer` will delay us. Not trying to downplay @aartaka`s expertise of course!

**Comment by aartaka** [comment]
> Regardless, I assume that re-writing something as fundamental as `search-buffer` will delay us. Not trying to downplay @aartaka's expertise of course!

It's fundamental, but the mechanism is pretty simple and similar to link hints (that's I've worked with already).

**Comment by Ambrevar** [comment]
OK to release `pre-release-1` on Monday?

**Comment by aartaka** [comment]
If we fix all the immediate bugs and merge #2408, then yes :)

**Comment by aadcg** [comment]
I must close #2328 before `pre-release-1`.

**Comment by Ambrevar** [comment]
@aadcg Do you think it's critical for the pre-release?  The pre-release has known bugs, but that's fine if we fix them for `3.0.0` in my opinion.

**Comment by aadcg** [comment]
Ok then, no worries!

**Comment by aartaka** [comment]
But then, is `restore-history-by-name` working?

**Comment by Ambrevar** [comment]
Should be fixed in #2450 too.

**Comment by Ambrevar** [comment]
`3-pre-release-1` is out! f024c4a3048f665baf973019ca2e49b615e5acf5

**Comment by Ambrevar** [comment]
Update: we're getting closer and closer!
Now most issues are either documentation stuff, trivial tweaks, or the fix is in the process of getting merged.

I've marked the remaining important and hard to fix issues as `high`:

https://github.com/atlas-engineer/nyxt/issues?q=is%3Aissue+is%3Aopen+label%3Ahigh+label%3A3.0

We've got some 4 issues left!
@aartaka Do you think you can help?

https://github.com/atlas-engineer/nyxt/issues/1794 I know how to fix.

**Comment by aartaka** [comment]
@jmercouris, I've pruned the 3.0.0 tag and deleted the release, because it's too early to make a release and most of the things (CI, changelog, packages etc.) that should be in a proper release are missing. Supported by @Ambrevar here.

Let's get back to the list of tasks above before actually making a release. Some of them duplicate the things in our (internal, see `release.org`) release guidelines, others are unique but not less important, especially testing things.

**Comment by jmercouris** [comment]
I'm sorry but that is not acceptable. We agreed to make a release. I spoke to Pierre on Monday, I had the OK from everyone on the team. It has been far too long, and it cannot be pushed *any* further.

**Comment by jmercouris** [comment]
The release is not dependent upon the issues completed here, it is dependent upon time.

**Comment by aartaka** [comment]
> I'm sorry but that is not acceptable. 

What's not acceptable is pushing tags for major release twice, second time after you've been told not to :D

> We agreed to make a release. 

We did, but not that sloppily. There is a release etiquette, and you're going against it. What's the use of making a release ASAP if it hurts our users to have an empty changelog and broken browser?

> I spoke to Pierre on Monday, I had the OK from everyone on the team. 

Not really. I've responded (In "Re: What's next?" at Mon, 08 May 2023 18:49:08 +0400) that we have to test that everything works before we move too fast and break too many things. That's at least not an OK from me.

> It has been far too long, and it cannot be pushed _any_ further.

Okay, if so, then let's fix as much as we can from this issue by a certain date (Thursday, for example) and make an all-rounded release that at least has a proper changelog and working commands and _does not look like a half-baked beta_. I mean, even our pre-releases look better than _this_.

**Comment by aartaka** [comment]
Yes, it's been too long, and I can share the frustration you feel. But now that we decided we're not including anything else in 3.0, let's polish what's there to an acceptable state and finally release it. Cutting corners on new features is okay, cutting corners on fixing outright broken code is not okay.

**Comment by jmercouris** [comment]
The cat is already out of the bag! We must release 3.0.1 with the fixes. We are getting a lot of people who are trying to download 3.0.0!

And yes, I did do it imprecisely! This is because the CI is broken and I am fighting it :-(

**Comment by aartaka** [comment]
> The cat is already out of the bag! We must release 3.0.1 with the fixes.

Fixes like a changelog for 3.0.0? That's hilarious.

> We are getting a lot of people who are trying to download 3.0.0!

Well let's shut the download link down to not disappoint them.

**Comment by aartaka** [comment]
I'm putting the cat back in the bag (pruning the tag out).

**Comment by jmercouris** [comment]
Artyom, we are on jitsi, can you please join so we can talk in real time?

**Comment by aartaka** [comment]
A small note on progress with @jmercouris: I'll manage all the changes from this issue and will make a proper release on Friday. If I don't fulfill some of the points here, we're releasing 3.0.0 without them on Friday.

**Comment by aadcg** [comment]
I've reported to Guix the [issue that stops us from being able to generate the self-contained bundle](https://issues.guix.gnu.org/63394).

**Comment by aartaka** [comment]
@aadcg, huge thanks for taking care of that `( ˘ ³˘)♥`

**Comment by Ambrevar** [comment]
> I'm sorry but that is not acceptable. We agreed to make a release. I spoke to Pierre on Monday, I had the OK from everyone on the team. It has been far too long, and it cannot be pushed _any_ further.

To clarify, I meant it was OK to make a release, which means _following_ release.org.  Pushing the tag is not enough.  Release is a process that has steps that must be followed.

Everyone, please calm down and do not escalate.  The good news is that a tag can be removed and we can fix this.

**Comment by aartaka** [comment]
Damn, we really did a huge chunk of work for 3.0...

**Comment by Ambrevar** [comment]
Haha, oh yes!

**Comment by aartaka** [comment]
Debugger is broken. Will fix.

**Comment by Ambrevar** [comment]
- [ ] IMPORTANT: Revert https://github.com/atlas-engineer/nyxt/commit/25a721b4b32dabdf23a8733fbd79621b8e628dbc.

**Comment by aartaka** [comment]
Debugger is fixed, all the modes are documented (some of the files in `source/` and `libraries/` are not, and documentation needs some fixes, but I'll get to these soon!), and changelog is updated—we're getting close to 3.0!

**Comment by aartaka** [comment]
Hmmmmm, [the release action](https://github.com/atlas-engineer/nyxt/actions/runs/4959548865/jobs/8873809025) fails with `cl-colors2` problem again. Anyone aware of what to do with that (CC @Ambrevar)?

And I'm afraid I have to be AFK for 3-4 hours. Anyone willing to pick the release up from there? It should be easy after CI builds properly, because then it's just easy stuff according to our `release.org` procedure.

If someone doesn't step up, I'll manage it when I get back :)

**Comment by Ambrevar** [comment]
- [ ] Merge #2955.  Necessary since otherwise the source won't be found by the Lisp image.

**Comment by Ambrevar** [comment]
> Hmmmmm, [the release action](https://github.com/atlas-engineer/nyxt/actions/runs/4959548865/jobs/8873809025) fails with `cl-colors2` problem again. Anyone aware of what to do with that (CC @Ambrevar)?

I tried contacting upstream, but opening an issue yields a 500 HTTP error.

I propose to mirror cl-colors2 at https://gitlab.common-lisp.net/nyxt.  Any better suggestion?

**Comment by aartaka** [comment]
Whaaaaaats going on, [Guix build fails](https://github.com/atlas-engineer/nyxt/actions/runs/4961785369/jobs/8879016982) 0_o

**Comment by jmercouris** [comment]
Are you still investigating this issue? What shall we do?

**Comment by aartaka** [comment]
I'm investigating and trying to fix it.

**Comment by aartaka** [comment]
I'll ping y'all in half an hour if I don't manage. But the backup plan in case I don't is:
- @aartaka (or @jmercouris): comment out the Guix phase and run the release.
- @jmercouris (and @aadcg): update website.
- @aadcg (or, possibly @Ambrevar, or @aartaka ): build Guix pack and upload it to the release page.

**Comment by jmercouris** [comment]
OK.

**Comment by jmercouris** [comment]
I've also updated your post with the tasks, you should be making the Guix pack, we can't rely on Andre or Pierre being available.

**Comment by aartaka** [comment]
Roger that!

**Comment by aartaka** [comment]
Damn, that's something extremely weird. I can even reproduce it locally. Guix basically doesn't work.

**Comment by aartaka** [comment]
Okay, I understand what's going on.

**Comment by jmercouris** [comment]
Good luck :-)

**Comment by aartaka** [comment]
[So the build seems to be going past the package build stage](https://github.com/atlas-engineer/nyxt/actions/runs/4963000951/jobs/8881751766), which is good and most probably means that it's gonna build alright. I'll sit there for a while and check that it builds. But if it takes, like, more than an hour from now, I'll go get some sleep.

Commit e277629b73c2dd2b4454d64e752bfb5e3498959c is what made the magic happen. Let's see if it builds. If it does, I'll apply it to `master` and will push a tag.

**Comment by aartaka** [comment]
It shouldn't take that much time...

**Comment by aartaka** [comment]
@jmercouris, I'm launching the Flatpak-only release action. It should run just fine. Get to the website ;)

I'll start a Guix pack build and will push it tomorrow morning. Hopefully it does compile :D

**Comment by aartaka** [comment]
[BEHOLD](https://github.com/atlas-engineer/nyxt/releases/tag/3.0.0)!

**Comment by aartaka** [comment]
Ah, okay, proot issue is still present. Then no Guix pack until they (whoever "they" are) fix it :P

**Comment by aartaka** [comment]
@jmercouris, the website is yours :)

**Comment by jmercouris** [comment]
OK, I'll handle it. Thank you Artyom!

**Comment by aadcg** [comment]
> Ah, okay, proot issue is still present. Then no Guix pack until they (whoever "they" are) fix it :P

I've hinted at how we could go around that issue [above](https://github.com/atlas-engineer/nyxt/issues/2303#issuecomment-1540698013).

I've published the self-contained bundle. It works on my machine, but  you (team) should test it too.

@aadcg 1 - 0 Nyxt CI
@aadcg 1 - 0 `guix pack`

**Comment by Ambrevar** [comment]
In my opinion the single most important 3-series issue that's left is #2296 (Common Settings).

**Comment by aadcg** [comment]
I agree with you. Me and @lansingthomas are finishing the spec for the new interactive tutorial and then I'll move to its implementation. We want to ship it within the 3-series.

So, up to this point, it seems that we're saying that #2296 and #2676 are a must for the 3-series. Anything else?

**Comment by aartaka** [comment]
All the red labels are to be fixed ASAP, so 3-series!

**Comment by aartaka** [comment]
I'd also say #2877, but I'm biased here :)
